---
title: CV
format:
  quarto-cv-pdf:
    output_file: "C:/Users/thoma/Dropbox/github_private/website/static/files/tb_cv.pdf"
author: Thomas J. Brailey
date: last-modified
#phone: +44 (0)7786 345 443 // +1 858 610 2437
#address: "Nuffield College New Road, Oxford, OX1 1NF"
email: thomasjbrailey@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
github: tjbrailey # github account
#orcid: 0000-0001-8538-8697 # orcid identifier
#osf: c9ptf # osf five character id
#twitter: twitter # twitter handle
web: tjbrailey.org
fontawesome: yes
nocite: '@*'
bibliography: 
  self: self_pubs.bib
  ra: ra_pubs.bib
  other: other_pubs.bib
validate-yaml: false
csl: apa-cv.csl
filters:
  - bold-author.lua
---

# Education

*University of Oxford*, PhD, Politics \hfill 2024-Present

*University of Oxford*, MPhil, Comparative Government (*with distinction*) \hfill 2022-2024

*University of California, San Diego*, B.S., Data Analytics/Political Science (*summa cum laude*) \hfill 2016-2020

# Employment

*International Organization for Migration*

&nbsp;&nbsp; Data and Research Intern \hfill 2026

*University of Oxford*

&nbsp;&nbsp; Tutor \hfill 2025-Present

*Payments and Governance Research Program*

&nbsp;&nbsp; Pre-Doctoral Fellow \hfill 2020-2022

**Research Assistantships**

&nbsp;&nbsp; *London School of Economics* \hfill 2025-Present

&nbsp;&nbsp; *University of Oxford* \hfill 2022-2024

&nbsp;&nbsp; *Center for the Study of African Political Economy* \hfill 2018-2020

&nbsp;&nbsp; *Center for Peace and Security Studies* \hfill 2018-2020

# Publications and Working Papers

::: {#refs-self}
:::

# Other Publications

::: {#refs-other}
:::

# Teaching Experience

Q-Step II (Data Analytics) (University of Oxford, 2027).

Q-Step I (Quantitative Social Science) (University of Oxford, 2026).

Politics of Sub-Saharan Africa [[Syllabus](https://www.dropbox.com/scl/fi/kdpz9gtizl9kawvx6ofcc/2025TT_pssa_syllabus.pdf?rlkey=9f8o4wifurtrib32oxmjdtffi&dl=0)] (University of Oxford, 2025-2027).

# Conferences, Workshop, Visiting Appointments

**Visiting Appointments:** Department of Politics, New York University (2026).

**Conferences:** *Junior Scholars in Quantitative Conflict* (2026), *Empirical Studies of Conflict* (2026), *American Political Science Association* (2021, 2026), *European Political Science Association* (2025, 2026), *European Political Science Society* (2026), *International Studies Association* (2020, 2021), *Midwestern Political Science Association* (2020, 2024, 2025), *Political Studies Association* (2023), *Southern California Research Conference* (2019), *Western Political Science Association* (2019).

# Awards and Scholarships

Winchester Grant (2026) (University of Oxford).

Research Training and Support Grant (2026) (Economic and Social Research Council).

Grand Union DTP Scholar 2024-2027 (Economic and Social Research Council).

Event Participant Grant 2024 (European Consortium for Political Research).

Cyril Foster Award 2024, 2026 (University of Oxford).

Merton College Research Grant 2023 (University of Oxford).

Clarendon Scholar 2022-2024 (University of Oxford).

BITSS Catalyst Grant Awardee 2021 (BITSS).

Sanford Lakoff Award for the Most Outstanding Senior Thesis 2020 (UC San Diego).

Pi Sigma Alpha 2017-2020 (UC San Diego).

Provost Honors 2016-2020 (UC San Diego).

Ernest C. Mort Leadership Excellence Award 2018 (UC San Diego).

# Service

**Journal reviewer:** *Journal of Conflict Resolution*, 2025.

**Conference/workshop chair:** *MPSA*, 2025.

**Conference/workshop discussant:** *Empirical Studies of Conflict* (2026), *T.E. Lawrence Program on the Study of Conflict* (2023-2026), *MPSA* (2025).

**Organizer:** *I4R Oxford Replication Games*, 2024.

# Fieldwork

Namibia (April 2026).

South Africa (March 2026).

<!-- # Training

European Consortium for Political Research (Social Network Analysis, 2024).

Oxford Spring School for Advanced Research Methods (Qualitative Methods, 2024).

European Consortium for Political Research (Bayesian Statistics, 2023).

Oxford Spring School for Advanced Research Methods (Machine Learning, 2023). -->

# Consulting

Africa Analyst: *Knightsbridge Strategic Group*, 2025.

# Skills

**Spoken languages**

&nbsp;&nbsp; English (native), French (beginner), Arabic (beginner).

**Technical languages**

&nbsp;&nbsp; *Proficient:* ArcGIS, Git, LaTeX, R, SPSS, STATA, SQL, Tableau, QGIS.

&nbsp;&nbsp; *Beginner:* Julia, Python, Stan.

**Infrastructures**

&nbsp;&nbsp; Amazon Web Services, Microsoft Office, Google Suite.

# References

\noindent
\begin{minipage}[t]{0.48\textwidth}
\textbf{Dr. Robin Harding}

Professor of Government

Lady Margaret Hall

University of Oxford

\href{mailto:robin.harding@politics.ox.ac.uk}{robin.harding@politics.ox.ac.uk}
\end{minipage}
\hfill
\begin{minipage}[t]{0.48\textwidth}
\textbf{Dr. Stathis Kalyvas}

Gladstone Professor of Government

All Souls College

University of Oxford

\href{mailto:stathis.kalyvas@politics.ox.ac.uk}{stathis.kalyvas@politics.ox.ac.uk}
\end{minipage}

\vspace{5pt}