---
name: Thomas J. Brailey
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: Bachelor of Scicnce
position: MPhil in Politics
address: Oxford, United Kingdom
email: thomasjbrailey@gmail.com
website: https://tjbrailey.netlify.app/
github: tjbrailey
linkedin: tjbrailey
twitter: tjbrailey
headcolor: "414141"
output: 
  vitae::awesomecv:
    keep_tex: true
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here("../", "Website", "public", "thomas_brailey_cv.pdf")) })
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates,
  "MPhil, Comparative Government", 
  "University of Oxford",
  "Oxford, United Kingdom", 
  "2022-2024",
  "Bachelor of Science, Political Science/Data Analytics",
  "University of California, San Diego",
  "San Diego, United States", 
  "2016-2020") %>% 
  detailed_entries(degree, dates, uni, loc)
```

# Research Experience

```{r consulting}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Research Assistant", 
  "University of Oxford", 
  "Oxford, United Kingdom", 
  "2022-Present", 
    list(
      "Co-authoring research with the Departments of Sociology and of Politics and International Relations.",
      "Conducting data cleaning, exploratory data analysis, and testing theoretical mechanisms with data.",
      "Transferring codebases to version-controlled GitHub setup."),
  "Pre-Doctoral Fellow", 
  "Payments and Governance Research Program", 
  "San Diego, United States", 
  "2020-2022", 
  list(
      "Conducted exploratory data analysis and data visualization across several research projects.",
      "Coordinated the transition of all code to GitHub and introducing RAs/GSRs to version control.",
      "Edited manuscripts and preparing presentations for government leaders and other stakeholders."),
  "Research Assistant", 
  "Center for the Study of African Political Economy", 
  "San Diego, United States", 
  "2018-2020", 
  list(
    "Independently developed a large-N database of election statistics across all recognized states.",
    "Used R to combine and reshape multiple datasets, visualize the data, and perform statistical analysis.",
    "Manually inputted missing data from newspapers and reports to ensure completeness of data."),
  "Research/Lab Assistant", 
  "Center for Peace and Security Studies", 
  "San Diego, United States", 
  "2018-2020", 
  list(
    "Used R to conduct quantitative analyses on large-N datasets.",
    "Generated graphs, tables, and figures in R and LaTeX for research papers and conference presentations.",
    "Wrote briefs on my data analysis and code and presented findings.")) %>% 
  detailed_entries(role, dates, company, loc, details)
```

## Publications-As Author

```{r}
bibliography_entries("pubs_author.bib")
```

## Publications-As Research Assistant

```{r}
bibliography_entries("pubs_ra.bib")
```

# Conference Invites

```{r talks}
tribble(
  ~ when, ~ details, ~ where,
  "2024", "Midwestern Political Science Association", "Chicago",
  "2023", "Political Science Association", "Virtual",
  "2021", "American Political Science Association", "Virtual",
  "2021", "International Studies Association", "Virtual",   
  "2020", "Midwestern Political Science Association", "Chicago, cancelled", 
  "2020", "International Studies Association", "Honolulu, cancelled",
  "2019", "Souther California Research Conference", "San Diego",
  "2019", "Western Political Science Association", "San Diego") %>% 
  brief_entries(details, when, where)
```

# Scholarship and Awards

```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Cyril Foster Award", "University of Oxford", "2024",
  "Research Grant", "University of Oxford", "2023",
  "Clarendon Scholarship", "University of Oxford", "2022-2024",
  "Catalyst Grant", "Berkeley Institute for Transparency in the Social Sciences", "2021",
  "Sanford Lakoff Award for the Most Outstanding Thesis", "UC San Diego", "2020",
  "Pi Sigma Alpha", "UC San Diego", "2017-2020",
  "Provost Honors", "UC San Diego", "2016-2020",
  "Outstanding Resident", "UC San Diego", "2017") %>%
  brief_entries(award, year, from)
```

# Volunteer Experience

```{r}
tribble(
  ~ what,
  "Volunteer data scientist for DataKind UK",
  "Co-found of the Political Science Student Association at UCSD",
  "Employment Assistant at the International Rescue Committee",
  "Tutor for San Diego's Refugee Tutoring Program") %>%
  brief_entries(what) 
```

# Training and Skills
## Training

```{r}
tribble(
  ~ what,
  "Oxford Spring School for Advanced Research Methods (Qualitative Methods, 2024)",
  "European Consortium for Political Research (Bayesian Statistics, 2023)",
  "Oxford Spring School for Advanced Research Methods (Machine Learning, 2023)") %>%
  brief_entries(what)
```
## Skills
### Spoken Languages

```{r}
tribble(
  ~ what,
  "English (Native), French (Beginner), Arabic (Beginner)") %>%
  brief_entries(what)
```

### Technical Languages

```{r}
tribble(
  ~ what,
  "Proficient: ArcGIS, Git, Latex, R, SPSS, STATA",
  "Beginner: Python, SQL, Tableau, Stan, Julia") %>%
  brief_entries(what)
```

### Softwares

```{r}
tribble(
  ~ what,
  "Amazon Web Services, Microsoft Office") %>%
  brief_entries(what)
```

<!--## Scholarships
```{r}
tribble(
  ~ scholarship, ~ from, ~ year,
  "Monash Graduate Excellence Scholarship", "Monash", "2023-2026",
  "Econometrics Honours Memorial Scholarship", "Monash", "2017",
  "Monash Community Leaders Scholarship", "Monash", "2015 & 2016",
  "Mitcham Rotary Scholarship", "Rotary", "2011 & 2012"
) %>%
  brief_entries(scholarship, year, from)
```

## Competitions
```{r}
tribble(
  ~ competition, ~ from, ~ year,
  "UseR! 2018 Datathon Champion", "UseR!", "2018",
  "RMIT SBITL Analytics Competition Champion", "RMIT", "2017",
  "RMIT SBITL Analytics Competition Champion", "RMIT", "2016"
) %>%
  brief_entries(competition, year, from)
```

<!--# Teaching experience

## University Tutoring

\begin{cvparagraph}
My teaching quality at Monash University has been consistently recognised with positive student evaluations and individual praise from my students. I generally teach applied forecasting and data analysis skills that give students a practical toolkit for working with data in industry. I have also been awarded seven congratulatory letters for outstanding student evaluations which indicates that the unit's teaching is among the best in the university.
\end{cvparagraph}
<!-- ```{r tutoring} -->
<!-- tribble( -->
<!--   ~ title, ~ code, ~ campus, ~ semester, ~ purple, -->
<!--   "Applied forecasting", "ETC3550/ETC5550", "Clayton", "2022 S1", TRUE, -->
<!--   "Communicating with Data", "ETC5523", "Clayton", "2021 S2", FALSE, -->
<!--   "Applied forecasting", "ETC3550/ETC5550", "Clayton", "2021 S1", TRUE, -->
<!--   "Communicating with Data", "ETC5523", "Clayton", "2020 S2", TRUE, -->
<!--   "Applied forecasting", "ETC3550/ETC5550", "Clayton", "2020 S1", TRUE, -->
<!--   "Advanced statistical modelling", "ETC3580", "Clayton", "2019 S2", TRUE, -->
<!--   "Data modelling and computing", "ETC1010", "Clayton", "2019 S2", FALSE, -->
<!--   "Data modelling and computing", "ETC1010", "Clayton", "2019 S1", FALSE, -->
<!--   "Applied forecasting for business and economics", "ETC3550/ETC5550", "Clayton", "2019 S1", TRUE, -->
<!--   "Data modelling and computing", "ETC1010", "Clayton", "2018 S2", FALSE, -->
<!--   "Advanced statistical modelling", "ETC3580", "Clayton", "2018 S2", TRUE, -->
<!--   "Business forecasting", "ETF3231/ETF5231", "Caulfield", "2018 S1", TRUE, -->
<!--   "Data modelling and computing", "ETC1010", "Clayton", "2017 S2", FALSE, -->
<!--   "Business forecasting", "ETF3231/ETF5231", "Caulfield", "2017 S1", FALSE, -->
<!--   "Mathematics for business", "ETF2700", "Caulfield", "2016 S2", FALSE, -->
<!--   "Business forecasting", "ETF3231/ETF5231", "Caulfield", "2016 S1", FALSE -->
<!-- ) %>%  -->
<!--   brief_entries(glue::glue("\\textbf{<code>}: <title> (Monash <campus>)", .open = "<", .close = ">"), semester, .protect = FALSE) -->
<!-- ``` -->

<!--\newpage

## Industry Workshops

\begin{cvparagraph}
In addition to sessional tutoring, I also teach data analysis workshops for industry professionals.
\end{cvparagraph}

```{r workshops}
tribble(
  ~ role, ~ course, ~ organisation, ~ country, ~ dates, ~ details,
  "Instructor", "Tidy Time Series and Forecasting in R", "NYR", "USA", "Jul. 2023", "Two day workshop on forecasting using tidy forecasting tools in R.",
  "Instructor", "Interactive web applications with Shiny", "WOMBAT", "Australia", "Dec. 2022", "Half-day workshop on the basics of shiny applications.",
  "Teaching assistant", "Tidy Time Series and Forecasting in R", "rstudio::conf", "USA", "Jan. 2020", "Two day workshop with Rob Hyndman on forecasting using tidyverse workflows.",
  "Instructor", "Interactive documents with Shiny", "CSIRO", "Australia", "Nov. 2019", "Two day intermediate workshop on developing of shiny applications.",
  "Instructor", "Data Wrangling", "Monash University", "Australia", "Sep. 2019", "A short workshop in the 'R Workshops for Beginners' series on using tidyr and dplyr to wrangle data.",
  "Helper", "Tidyverse developer day", "RStudio", "France", "Jul. 2019", "A one day developer day where I helped R users resolve issues on tidyverse packages.",
  "Teaching assistant", "High-dimensional time series analysis", "ISI WSC", "Malaysia", "Aug. 2019", "One day short course with Rob Hyndman for analysing and forecasting large collections of time series."
  # "Instructor", "The grammar of animation", "Monash University", "Australia", "Mar. 2019", "A short workshop for NUMBAT group on creating animated graphics in R with the gganimate package.",
  # "Teaching assistant", "Master R Developer Workshop", "RStudio", "Australia", "Dec. 2016", "A two day workshop with Hadley Wicham on programming with R and developing R packages.",
) %>% 
  brief_entries(glue::glue("\\textbf{<course>}: <role> (<organisation>, <country>) \\newline <details>", .open = "<", .close = ">"), paste0(dates, "\\newline"), .protect = FALSE)
```


# Research output
## Software

\begin{cvparagraph}
My primary research output is the translation of academic research into open source software packages. In total I have been the lead developer or a substantial contributor to more than 20 open source R packages, many of which provide tools for analysing time series data and visualisations. This software has a significant impact to the industry, with the total average unique monthly downloads exceeding 100,000.
\end{cvparagraph}

```{r r-pkgs, include = FALSE}
tribble(
  ~ pkg, ~ when, ~ role, ~ details,
  "gghdr", "2022", "Author", "Extends ggplot2 with plot types for visualising highest density regions.",
  "distributional", "2020", "Lead developer", "Vectorised distribution objects with methods for manipulating and computing on probability distributions.",
  "fable", "2019", "Lead developer", "A collection of time series models for use in a tidyverse workflow.",
  "fable.prophet", "2019", "Lead developer", "Extension package implementing the prophet forecasting procedure for fable.",
  "feasts", "2019", "Lead developer", "A collection of features, decompositions, statistics and graphics tools for the analysing tidy time series data.",
  "fabletools", "2019", "Lead developer", "Provides common utilities for the fable forecasting framework, allows users to extend fable with new models.",
  "tsibbledata", "2019", "Lead developer", "Diverse datasets in a tidy time series data structure (tsibble). Useful in examples of tidy time series analysis.",
  "tsfeatures", "2019", "Author", "Various methods for extracting features from time series data.",
  "tsibble", "2018", "Contributor", "Tidy temporal data structures and tools. The data for the tidy time series collection of packages.",
  "vitae", "2018", "Lead developer", "Dynamically generate a Résumé or CV using R Markdown. This CV is created using code with that package!",
  "cransays", "2018", "Author", "Provides a dashboard and historical data for R packages being reviewed by CRAN.",
  "fasster", "2017", "Lead developer", "Implementation of the FASSTER model for forecasting complex multiple seasonal patterns.",
  "icons", "2017", "Lead developer", "Embed SVG icons in R documents such as slides, reports and apps.",
  "taipan", "2018", "Lead developer", "Generates shiny apps for annotating image data, which is useful for training machine learning models.",
  "ggquiver", "2017", "Lead developer", "Extends ggplot2 for displaying vector fields on plots.",
  "forecast", "2015", "Author", "Methods and tools analysing univariate time series data and producing model-based forecasts."
) %>% 
  brief_entries(glue::glue("\\textbf{<pkg>}: <role> \\newline <details>", .open = "<", .close = ">"), paste0(when, "\\newline"), .protect = FALSE)
```

<!-- ## Academic research -->

<!-- fasster, taipan, fable -->

<!-- # Data analysis projects -->

<!-- # Related interests -->
<!-- * Home automation -->
<!-- * Beekeeping -->
<!-- * Permaculture -->
<!-- * Electronics design -->
<!-- * Woodworking -->

<!-- # Relevant Skills -->
<!-- ```{r} -->
<!-- cvskill("Data Analysis", c("Visualisation", "Data Cleaning", "Forecasting", "Modelling", "Communication", "Inference", "Machine Learning", "Web Scraping")) -->
<!-- cvskill("Programming", c("R", "Python", "SQL", "Java", "C", "C++", "HTML/CSS", "TeX", "MATLAB")) -->
<!-- ``` -->

<!--\newpage

--> 
